Node name is a required value
This avoids this error:
ERROR: Fog::Compute::Linode::Error: A Linode label may only contain ASCII letters or numbers, dashes, and underscores, must begin and end with letters or numbers, and be at least three characters in length.

Signed-off-by: Tim Smith <tsmith@chef.io>